### ISSUE TITLE
Setting NODE_ENV in buildConfig doesn't seem to affect npm install in assemble script

### ISSUE THREAD

**Issue by grdryn** [openshift/sti-nodejs#64]
Setting `NODE_ENV` env var to `production` should make npm only install devDependencies when running `npm install`. In the `sourceStrategy` section of my BuildConfig, I've added the following, [according to the docs](https://docs.openshift.org/latest/dev_guide/builds.html#buildconfig-environment):

```
"env": [
    {
        "Name": "NODE_ENV",
        "Value": "production"
    }
]
```

This doesn't seem to have any affect on the `npm install -d` that's run at the [end of the assemble script](https://github.com/openshift/sti-nodejs/blob/master/0.10/.sti/bin/assemble#L29), as my devDependencies are still being installed.

**Comment by mfojtik** [comment]
@grdryn what you did is correct and should work. I wonder whether the environment variable was passed down to the S2I builder container. @jhadvig can you please verify that?

**Comment by grdryn** [comment]
@mfojtik Thanks for replying.

To clarify, we've tried putting that env object both at `spec.strategy.sourceStrategy`, as that's where sourceStrategy is located [here](https://docs.openshift.org/latest/dev_guide/builds.html#defining-a-buildconfig), and also tried copying that sourceStrategy object to the top level of the buildConfig object. In both of those cases, npm dev dependencies are being installed.

The reason that we noticed this is that currently one of our dev dependencies has an issue and results in npm erroring out.

**Comment by grdryn** [comment]
I assume there must be cases where the devDependencies are useful with this, or would it make sense to add `--production` to the npm install command?

**Comment by grdryn** [comment]
I've also tried setting an additional env var to check that it wasn't just an npm issue:

```
{
    "Name": "npm_config_production",
    "Value": "true"
}
```

This should do the same thing as the NODE_ENV one, but dev dependencies still get installed.

**Comment by grdryn** [comment]
Here's the outline of our BuildConfig definition (with irrelevant sections removed):

```
{
  "kind": "BuildConfig",
  "spec": {
    "strategy": {
      "type": "Source",
      "sourceStrategy": {
        "from": {
          "kind": "ImageStreamTag",
          "namespace": "openshift",
          "name": "nodejs:0.10"
        },
        "env": [
          {
            "Name": "NODE_ENV",
            "Value": "production"
          },
          {
            "Name": "npm_config_production",
            "Value": "true"
          }
        ]
      }
    },
  }
}
```

Does this look okay, or have I put something in the wrong place? Thanks again for any input! :)

**Comment by mfojtik** [comment]
@grdryn lowercase "name" ;-)

**Comment by mfojtik** [comment]
@grdryn sorry, our documentation is wrong... @jhadvig will fix it.

**Comment by jhadvig** [comment]
Fix already provided. https://github.com/openshift/openshift-docs/pull/931
Sorry for this.

**Comment by grdryn** [comment]
@mfojtik @jhadvig Cool, thanks a lot, that worked :+1: 

We originally tried with lowercase, but it sounds like we may have had it in th wrong place back then.

**Comment by jhadvig** [comment]
@grdryn glad to hear that it worked :)

**Comment by bparees** [comment]
Is the build log level example wrong too?  I've referred people to that and never had it not work...

**Comment by bparees** [comment]
I guess everyone else ignored the case.   Thanks for the fix, Jakub.

**Comment by jhadvig** [comment]
@bparees I've updated examples in both sections, Build Logs and BuildConfig Environment

**Comment by jhadvig** [comment]
Closing this issue since the fix has been merged
