### ISSUE TITLE
include scripts in image

### ISSUE THREAD

**Issue by bparees** [openshift/sti-nodejs#7]
didn't we decide for our images we'd bake the STI scripts into the image rather than download them?  you can still easily override them, but it would improve the speed+reliability of builds using this image.

**Comment by soltysh** [comment]
And testability. Yes we agreed on having them inside.

**Comment by mfojtik** [comment]
+1

**Comment by jhadvig** [comment]
@bparees true, will bake them it into the image. The question is where to put them? My first guess would be `/opt/nodejs/bin/` cause we are already putting the `usage` script there. On the other hand we where speaking with @mfojtik and he suggested the `/usr/bin` would be more appropriate. 
Thoughts ?

**Comment by bparees** [comment]
Hmm, i thought we had some sort of .sti dir standard we'd established?

Barring that, I sort of prefer /opt/nodejs/bin so we keep our stuff collected together, much iike v2 cartridges.

**Comment by mfojtik** [comment]
@jhadvig @bparees I would argue for /usr/local as the /opt/nodejs might collide with things. Also I'm not sure if this is not too late, but I would like to make the commands more explicit in name:

```
/usr/local/bin/sti-run
/usr/local/bin/sti-assemble
/usr/local/bin/sti-save-artifacts
```

In this case they can even live in /usr/bin. I don't like abusing /opt as this directory is [reserved](http://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/opt.html) for "third party applications", but I don't think STI is in this category.

**Comment by bparees** [comment]
it may be too late as we do have people building images already.

not sure how /usr/bin is less likely to collide with things than /opt/nodejs.  

In fact that argument makes me even more in favor of including sti.  

how about /usr/local/sti  ?

**Comment by mfojtik** [comment]
@bparees /usr/local/sti is to me better choice :)

**Comment by soltysh** [comment]
:+1: for `/usr/local/sti` since there's not need to have it in `$PATH` as we're giving full path to dir containing the scripts with `STI_SCRIPTS_URL`.

:-1: for changing script names.

**Comment by jhadvig** [comment]
Taking care of in: https://github.com/jhadvig/sti-nodejs/commit/1029a8fe81289c387ccd59d41a5e477cb89d5d8b

**Comment by jhadvig** [comment]
@bparees the change has been merged. Closing this issue
