### ISSUE TITLE
APP_ROOT unneeded?

### ISSUE THREAD

**Issue by bparees** [openshift/sti-nodejs#8]
With the new STI support for a contextDir, do we really need each image to support something like APP_ROOT?  Is there a use case where you might want to include the entire repository, but specify a subdirectory for actually running?  I'm thinking not, so we could simplify the implementation slightly by removing this (and not doing it in other images either).

**Comment by soltysh** [comment]
:+1:

**Comment by mfojtik** [comment]
yeah, we should remove all mentions of APP_ROOT right after the updated STI with contexDir support is pushed into Origin.

**Comment by jhadvig** [comment]
Taken care of this one in: https://github.com/jhadvig/sti-nodejs/commit/20d880cf0a20fa04f1e8ca0682b2c44a114d34ba

**Comment by jhadvig** [comment]
@bparees the change has been merged. Closing this issue.
