### ISSUE TITLE
add 'bower install' command to sti builder

### ISSUE THREAD

**Issue by rimolive** [openshift/sti-nodejs#82]

**Comment by php-coder** [comment]
@rimolive @bparees Could I ask you to explain the issue? It's not clear for me what is broken and what we need to fix.

**Comment by mfojtik** [comment]
@php-coder http://bower.io another package manager for nodejs (in addition to npm). We need to make sure it is packaged for RHEL7. CC @humaton

**Comment by rimolive** [comment]
@php-coder Nothing to fix in my opinion, but add an extra feature.

@mfojtik unfortunately it is not packaged for RHEL7 yet. Any considerations to always use the RHEL7 package instead of "npm install" it?

**Comment by mfojtik** [comment]
@rimolive we are trying to keep the centos7 and rhel7 versions of the nodejs image in sync. But you can however fork this repo and just npm install bower during the image build. You can also `npm install bower` in the assemble script, which in that case the bower will be installed in the user home directory.

**Comment by humaton** [comment]
Use standard way of including packages in rhel please fill RFE in bugzilla. My estimate is that if you get bower in rhel it won't be sooner then jun/july.

**Comment by elyscape** [comment]
You could add [a postinstall script](https://docs.npmjs.com/misc/scripts) to your package.json file that runs `bower install`.

**Comment by mfojtik** [comment]
@rimolive can you please describe the use case for what you need the `bower` for?

**Comment by bparees** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1304796

**Comment by rimolive** [comment]
@mfojtik as you said bower is like npm, but for front-end dependencies. There you can:

* Install front-end packages (like AngularJS)
* Copy the files to a public directory where your Node.js app can reach the files.

I know that if we consider add all package managers it will take a lot of time and effort to do that, but I see bower as essential to a Node.js developer usage.

**Comment by elyscape** [comment]
All you need to do is add bower to your package.json file as a dependency and then add a postinstall script to that runs `bower install`. You don't need it in the image proper.

**Comment by kasicka** [comment]
Are you sure webpack wouldn't be a better solution? Bower seems a little unmaintained and its' dependencies are outdated and contain lot of vulnerabilities.

**Comment by elyscape** [comment]
Neither is necessary. All you need to do is add them to your package.json file and then add the relevant install command to the postinstall script.

**Comment by ryanj** [comment]
I might have a fix in #88 - you'd just need to document all of your dependencies (including any "globals") in your package.json.

**Comment by bparees** [comment]
closing based on @elyscape and @ryanj's suggestion (and the fix that went in to enable invoking bower after installing it as a dep)
