### ISSUE TITLE
add $HOME/node_modules/.bin to the PATH

### ISSUE THREAD

**Issue by ryanj** [openshift/sti-nodejs#87]
This should provide a fix for #82

**Comment by elyscape** [comment]
This shouldn't be necessary. npm adds this to the PATH when executing the scripts in package.json.

**Comment by ryanj** [comment]
@elyscape the use case I'm trying to solve is to provide CLI access to scripts - so users won't need to use the "global" installation mode ("npm i -g grunt-cli" or "npm i --global gulp-cli") in order to make grunt, gulp, or bower available to their shell.

**Comment by elyscape** [comment]
Gotcha. That makes sense.

**Comment by bparees** [comment]
fixed by https://github.com/openshift/sti-nodejs/pull/88
